// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_o67rWkNoN29qrZddSFbis65fN3JZ-w',
    appId: '1:805556344248:web:cf06271e068acd21796b4d',
    messagingSenderId: '805556344248',
    projectId: 'studentmanagerweek12',
    authDomain: 'studentmanagerweek12.firebaseapp.com',
    storageBucket: 'studentmanagerweek12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZjpnXyn5eIP61fDHjApgSo0q7odmaE0',
    appId: '1:805556344248:android:6a62421c8d660ad1796b4d',
    messagingSenderId: '805556344248',
    projectId: 'studentmanagerweek12',
    storageBucket: 'studentmanagerweek12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFrHh25ZkblcJGn1DOcIyNWYPT4Om-qM',
    appId: '1:805556344248:ios:ce08e112c7c5fc32796b4d',
    messagingSenderId: '805556344248',
    projectId: 'studentmanagerweek12',
    storageBucket: 'studentmanagerweek12.appspot.com',
    iosBundleId: 'com.example.week12StudentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFrHh25ZkblcJGn1DOcIyNWYPT4Om-qM',
    appId: '1:805556344248:ios:ce08e112c7c5fc32796b4d',
    messagingSenderId: '805556344248',
    projectId: 'studentmanagerweek12',
    storageBucket: 'studentmanagerweek12.appspot.com',
    iosBundleId: 'com.example.week12StudentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh_o67rWkNoN29qrZddSFbis65fN3JZ-w',
    appId: '1:805556344248:web:15bf6b625b6236e2796b4d',
    messagingSenderId: '805556344248',
    projectId: 'studentmanagerweek12',
    authDomain: 'studentmanagerweek12.firebaseapp.com',
    storageBucket: 'studentmanagerweek12.appspot.com',
  );
}
